name: Deploy Batch Builder Function

on:
  push:
    branches:
      - main
    paths:
      - 'functions/batch_builder_function/**'
      - 'shared_libs/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: gen-lang-client-0306766464
        # Option 1: Authenticate using Workload Identity Federation (Recommended)
        # workload_identity_provider: projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/POOL_ID/providers/PROVIDER_ID
        # service_account: github-actions-deployer@gen-lang-client-0306766464.iam.gserviceaccount.com

        # Option 2: Authenticate using a service account key (Less Secure, but uses user's specified method)
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

    - name: Deploy Cloud Function
      uses: google-github-actions/deploy-cloud-functions@v2
      with:
        name: build-batch-request
        runtime: python39
        entry_point: build_batch_request
        source_dir: functions/batch_builder_function
        trigger_topic: session-data-created
        region: us-central1
        env_vars: |
          GOOGLE_CLOUD_PROJECT=gen-lang-client-0306766464,
          GCS_BUCKET_NAME=your-session-data-bucket,
          BATCH_PROCESSING_REQUESTS_TOPIC=batch-processing-requests,
          NEWS_DATA_ROOT_PREFIX=news_data/,
          BATCH_PROCESSING_SUBFOLDER=batch_processing/
        service_account: svc-account-aisports@gen-lang-client-0306766464.iam.gserviceaccount.com
        gen2: true


